# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roberts', '0002_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('script', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roberts.Tema')),
            ],
            options={
                'verbose_name_plural': 'contenidos',
            },
        ),
    ]
