# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 21:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('roberts', '0003_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='script',
            field=tinymce.models.HTMLField(),
        ),
    ]
